"""NotebookPack types + generation entry point."""

from __future__ import annotations

import importlib.util
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Iterable

from deltasci.hypothesis import GroundedHypothesis
from deltasci.packs import DomainPack
from deltasci.protocol import ExperimentPlan

NOTEBOOK_FILENAME = "notebook.py"
REQUIREMENTS_FILENAME = "requirements.txt"


@dataclass
class NotebookPack:
    """Filesystem locations for a generated notebook bundle.

    Always written to `<run_dir>/10_notebook/`. Top-level run dir gets no
    convenience copy — notebooks are explicitly tied to one stage subdir to
    avoid the impression they're a "primary" artifact.
    """

    notebook_path: Path
    requirements_path: Path
    readme_path: Path
    pack_name: str
    cell_count: int = 0
    parameters_substituted: dict[str, Any] = field(default_factory=dict)


def pack_has_notebook_template(pack: DomainPack) -> bool:
    if pack.source_path is None:
        return False
    return (pack.source_path / NOTEBOOK_FILENAME).is_file()


def _load_pack_notebook_module(pack: DomainPack):
    if pack.source_path is None:
        return None
    notebook_py = pack.source_path / NOTEBOOK_FILENAME
    if not notebook_py.is_file():
        return None
    # Use a unique module name per pack so multiple packs don't clobber each other.
    spec = importlib.util.spec_from_file_location(
        f"deltasci_pack_notebook_{pack.name}", str(notebook_py)
    )
    if spec is None or spec.loader is None:
        return None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _wrap_cells_into_ipynb(cells: Iterable[dict]) -> dict:
    """Wrap a list of cell dicts into a complete nbformat-4 notebook."""

    return {
        "cells": list(cells),
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
            "deltasci_generated": True,
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def _scaffold_readme(hypothesis: GroundedHypothesis, pack_name: str) -> str:
    return (
        "# Notebook scaffold\n"
        "\n"
        "**This notebook is a scaffold generated by deltasci. The AI did not run it.**\n"
        "\n"
        "Every step is parameterized from the deltasci-generated experiment plan, but the\n"
        "concrete analysis logic — actual data loading, model architecture, metric\n"
        "computation, figure generation — is your job. Look for `# TODO` comments;\n"
        "they mark the substantive customizations the scaffold cannot do for you.\n"
        "\n"
        "The scaffold is **correct by construction** in the boilerplate (imports, data\n"
        "structures, evaluation framing). The AI's contribution is filling in plan-derived\n"
        "parameters (datasets, thresholds, baselines) — not authoring novel analysis code.\n"
        "\n"
        "## What this notebook references\n"
        "\n"
        f"- Domain pack: `{pack_name}`\n"
        f"- Hypothesis: {hypothesis.title}\n"
        f"- Falsifiability threshold: {hypothesis.falsifiability.threshold}\n"
        f"- Null outcome: {hypothesis.falsifiability.null_outcome}\n"
        "\n"
        "## To run\n"
        "\n"
        "```bash\n"
        "python -m venv .venv\n"
        "source .venv/bin/activate\n"
        "pip install -r requirements.txt\n"
        "jupyter lab notebook.ipynb\n"
        "```\n"
        "\n"
        "## Audit-pillar relationship\n"
        "\n"
        "The dataset accessions and method citations baked into the scaffold are the\n"
        "same ones in `06_protocol/experiment_plan.json` — and they have already been\n"
        "audited against PubMed / Crossref / GitHub / GEO. See `08_audits/citations.json`\n"
        "for verification status before relying on them.\n"
    )


def generate_notebook_pack(
    *,
    pack: DomainPack,
    hypothesis: GroundedHypothesis,
    plan: ExperimentPlan,
    run_dir: Path,
) -> NotebookPack | None:
    """Generate `<run_dir>/10_notebook/{notebook.ipynb,requirements.txt,README.md}`.

    Returns None if the pack has no `notebook.py` template.
    """

    module = _load_pack_notebook_module(pack)
    if module is None:
        return None
    builder: Callable[..., list[dict]] | None = getattr(module, "build_cells", None)
    if builder is None:
        return None

    cells = builder(hypothesis=hypothesis, plan=plan)
    if not isinstance(cells, list):
        raise TypeError(f"pack {pack.name!r} build_cells() must return list[dict], got {type(cells)}")

    notebook = _wrap_cells_into_ipynb(cells)

    out_dir = run_dir / "10_notebook"
    out_dir.mkdir(parents=True, exist_ok=True)
    notebook_path = out_dir / "notebook.ipynb"
    notebook_path.write_text(json.dumps(notebook, indent=1, ensure_ascii=False), encoding="utf-8")

    requirements_path = out_dir / REQUIREMENTS_FILENAME
    if pack.source_path is not None and (pack.source_path / REQUIREMENTS_FILENAME).is_file():
        requirements_path.write_text(
            (pack.source_path / REQUIREMENTS_FILENAME).read_text(encoding="utf-8"), encoding="utf-8"
        )
    else:
        requirements_path.write_text("# (pack ships no requirements.txt — fill in manually)\n", encoding="utf-8")

    readme_path = out_dir / "README.md"
    readme_path.write_text(_scaffold_readme(hypothesis, pack.name), encoding="utf-8")

    return NotebookPack(
        notebook_path=notebook_path,
        requirements_path=requirements_path,
        readme_path=readme_path,
        pack_name=pack.name,
        cell_count=len(cells),
        parameters_substituted={
            "hypothesis_title": hypothesis.title,
            "primary_metric": plan.primary_metric,
            "success_threshold": plan.success_threshold,
            "primary_dataset": plan.data_acquisition.primary_dataset,
            "step_count": len(plan.steps),
            "baseline_count": len(plan.baselines),
        },
    )
