"""Biomed notebook scaffold.

Discipline (v0.3.1):
- **Real working code** for canonical workflow steps where AI is well-covered:
  scRNA-seq QC, normalization, dimensionality reduction, clustering, marker
  scoring, spatial-neighbor graphs, sklearn evaluation. These are textbook
  patterns; every scanpy tutorial implements them identically.
- **TODO markers** only for substantive customizations the AI cannot reliably
  produce: your specific marker panel for cell typing, your specific model
  architecture, your specific threshold values.

Step-name keyword detection routes each protocol step to a step-specific code
emitter. Steps whose names don't match any known canonical pattern fall back
to a generic stub.
"""

from __future__ import annotations

from deltasci.hypothesis import GroundedHypothesis
from deltasci.notebook.cells import code_cell, markdown_cell
from deltasci.protocol import ExperimentPlan, ProtocolStep


def build_cells(hypothesis: GroundedHypothesis, plan: ExperimentPlan) -> list[dict]:
    cells: list[dict] = []

    cells.append(markdown_cell(
        f"# {hypothesis.title}\n"
        f"\n_Notebook scaffold generated by deltasci. Canonical workflow code is real; "
        f"`# TODO` markers indicate where substantive customization is required._\n"
        f"_See `README.md` for orientation._\n"
    ))

    cells.append(markdown_cell(
        "## Hypothesis\n\n"
        f"{hypothesis.statement}\n\n"
        "### Falsifiability\n"
        f"- **Prediction:** {hypothesis.falsifiability.prediction}\n"
        f"- **Threshold:** {hypothesis.falsifiability.threshold}\n"
        f"- **Null outcome:** {hypothesis.falsifiability.null_outcome}\n"
    ))

    cells.append(code_cell(_imports_cell()))
    cells.append(markdown_cell(_data_acquisition_md(plan)))
    cells.append(code_cell(_data_acquisition_code(plan)))

    for step in plan.steps:
        cells.append(_step_markdown(step))
        cells.append(code_cell(_route_step_code(step)))

    cells.append(markdown_cell("## Falsifiability check\n"))
    cells.append(code_cell(_falsifiability_code(plan)))

    cells.append(markdown_cell(
        "## Notes\n\n"
        "When you've filled in the TODOs and the falsifiability check passes:\n\n"
        "1. Re-audit with `deltasci audit <run-dir> --write` so the citation audit\n"
        "   reflects any new datasets or references you wired in.\n"
        "2. Consider archiving and starting a fresh deltasci pass with `deltasci run\n"
        "   --iterate-on <this-run-dir>` so the iteration history captures the change.\n"
    ))

    return cells


# ---- Header / shared cells -------------------------------------------------


def _imports_cell() -> str:
    return (
        "# === Imports — life-sciences + ML stack ===\n"
        "import numpy as np\n"
        "import pandas as pd\n"
        "import matplotlib.pyplot as plt\n"
        "\n"
        "import anndata as ad\n"
        "import scanpy as sc\n"
        "# import squidpy as sq  # uncomment for spatial transcriptomics\n"
        "\n"
        "from sklearn.metrics import (\n"
        "    roc_auc_score, average_precision_score, brier_score_loss,\n"
        "    confusion_matrix, classification_report,\n"
        ")\n"
        "from sklearn.model_selection import StratifiedKFold\n"
        "\n"
        "import torch\n"
        "import torch.nn as nn\n"
        "# import torch_geometric as pyg  # uncomment for graph-based architectures\n"
        "\n"
        "sc.settings.verbosity = 1\n"
        "sc.settings.set_figure_params(dpi=100, frameon=False)\n"
        "\n"
        "RANDOM_SEED = 0\n"
        "np.random.seed(RANDOM_SEED)\n"
        "torch.manual_seed(RANDOM_SEED)\n"
    )


def _data_acquisition_md(plan: ExperimentPlan) -> str:
    return (
        "## Data acquisition\n\n"
        f"- **Primary dataset:** {plan.data_acquisition.primary_dataset or '(not specified)'}\n"
        f"- **Accession / URL:** `{plan.data_acquisition.accession_or_url or '—'}`\n"
        f"- **Access constraints:** {plan.data_acquisition.access_constraints or '—'}\n"
    )


def _data_acquisition_code(plan: ExperimentPlan) -> str:
    accession = plan.data_acquisition.accession_or_url or ""
    return (
        "# === Data acquisition ===\n"
        f"PRIMARY_ACCESSION = {accession!r}\n"
        "DATA_PATH = None  # TODO: set local .h5ad path or download URL\n"
        "CLINICAL_CSV = None  # TODO: set path to clinical metadata CSV (patient_id, outcome)\n"
        "\n"
        "if DATA_PATH is None:\n"
        "    raise NotImplementedError(\n"
        "        f'Set DATA_PATH for accession {PRIMARY_ACCESSION}. '\n"
        "        'See 06_protocol/protocol.md and 08_audits/citations.json for verification status.'\n"
        "    )\n"
        "\n"
        "adata = sc.read_h5ad(DATA_PATH)\n"
        "print(f'loaded: {adata.n_obs} cells × {adata.n_vars} genes')\n"
        "print(f'available .obs columns: {list(adata.obs.columns)}')\n"
        "\n"
        "if CLINICAL_CSV is not None:\n"
        "    clinical = pd.read_csv(CLINICAL_CSV)\n"
        "    print(f'clinical: {len(clinical)} patients, {clinical.columns.tolist()}')\n"
    )


# ---- Step routing ----------------------------------------------------------


def _step_markdown(step: ProtocolStep) -> dict:
    parts = [f"## Step {step.order}: {step.name}"]
    if step.description:
        parts.extend(["", step.description])
    if step.inputs:
        parts.extend(["", f"**Inputs:** {', '.join(step.inputs)}"])
    if step.outputs:
        parts.append(f"**Outputs:** {', '.join(step.outputs)}")
    if step.method_citations:
        parts.extend(["", "**Methods cited:**"])
        for c in step.method_citations:
            parts.append(f"- {c}")
    return markdown_cell("\n".join(parts) + "\n")


def _route_step_code(step: ProtocolStep) -> str:
    name = (step.name + " " + (step.description or "")).lower()
    if any(k in name for k in ("cohort", "assembly", "linkage", "clinical")):
        return _step_cohort(step)
    if any(k in name for k in ("qc", "quality", "filter", "preprocess")):
        return _step_qc(step)
    if any(k in name for k in ("annotation", "cell-type", "celltype", "clustering", "leiden")):
        return _step_annotation(step)
    if any(k in name for k in ("spatial", "neighbor", "graph construction")):
        return _step_spatial_graph(step)
    if any(k in name for k in ("train", "model", "fit", "encoder", "hgt", "gnn")):
        return _step_train(step)
    if any(k in name for k in ("evaluat", "metric", "calibration", "auroc", "auc", "auprc")):
        return _step_evaluate(step)
    return _step_generic(step)


# ---- Step-specific code emitters -------------------------------------------


def _step_cohort(step: ProtocolStep) -> str:
    return (
        f"# === Step {step.order}: {step.name} ===\n"
        "# Canonical pattern: assemble per-patient cohort with linked outcomes.\n"
        "\n"
        "OUTCOME_COL = 'response'  # TODO: rename to your outcome column\n"
        "PATIENT_ID_COL = 'patient_id'  # TODO: rename if your column differs\n"
        "\n"
        "if CLINICAL_CSV is None:\n"
        "    raise NotImplementedError('Set CLINICAL_CSV in the data-acquisition cell.')\n"
        "\n"
        "clinical = pd.read_csv(CLINICAL_CSV)\n"
        "assert OUTCOME_COL in clinical.columns, f'Outcome column {OUTCOME_COL!r} missing'\n"
        "assert PATIENT_ID_COL in clinical.columns, f'Patient-ID column {PATIENT_ID_COL!r} missing'\n"
        "\n"
        "n = len(clinical)\n"
        "print(f'cohort size: {n} patients')\n"
        "if clinical[OUTCOME_COL].dtype != object:\n"
        "    print(f'positive-class rate: {(clinical[OUTCOME_COL] == 1).mean():.1%}')\n"
        "\n"
        "if PATIENT_ID_COL in adata.obs.columns:\n"
        "    adata.obs = adata.obs.merge(\n"
        "        clinical[[PATIENT_ID_COL, OUTCOME_COL]],\n"
        "        on=PATIENT_ID_COL, how='left',\n"
        "    )\n"
        "    print(f'cells with linked outcome: {adata.obs[OUTCOME_COL].notna().sum()}/{adata.n_obs}')\n"
        "else:\n"
        "    print(f'WARNING: adata.obs has no {PATIENT_ID_COL!r}; merge manually before continuing.')\n"
    )


def _step_qc(step: ProtocolStep) -> str:
    return (
        f"# === Step {step.order}: {step.name} ===\n"
        "# Canonical scanpy QC: per-cell + per-gene filters, normalization, log1p.\n"
        "\n"
        "MIN_GENES_PER_CELL = 200  # TODO: tune for your platform (Xenium ~30, scRNA ~200-500)\n"
        "MIN_CELLS_PER_GENE = 3\n"
        "MAX_PCT_MITO = 20.0       # TODO: tune (15-25% is common for fresh tissue)\n"
        "TARGET_SUM = 1e4\n"
        "\n"
        "n_pre = adata.n_obs\n"
        "\n"
        "mt_prefix = 'MT-' if any(g.startswith('MT-') for g in adata.var_names) else 'mt-'\n"
        "adata.var['mt'] = adata.var_names.str.startswith(mt_prefix)\n"
        "sc.pp.calculate_qc_metrics(adata, qc_vars=['mt'], inplace=True, percent_top=None, log1p=False)\n"
        "\n"
        "sc.pp.filter_cells(adata, min_genes=MIN_GENES_PER_CELL)\n"
        "sc.pp.filter_genes(adata, min_cells=MIN_CELLS_PER_GENE)\n"
        "adata = adata[adata.obs['pct_counts_mt'] < MAX_PCT_MITO, :].copy()\n"
        "\n"
        "sc.pp.normalize_total(adata, target_sum=TARGET_SUM)\n"
        "sc.pp.log1p(adata)\n"
        "\n"
        "n_post = adata.n_obs\n"
        "print(f'QC: {n_pre} → {n_post} cells ({100*(n_pre-n_post)/n_pre:.1f}% removed)')\n"
        "print(f'genes retained: {adata.n_vars}')\n"
        "\n"
        "adata.layers['log1p'] = adata.X.copy()\n"
    )


def _step_annotation(step: ProtocolStep) -> str:
    return (
        f"# === Step {step.order}: {step.name} ===\n"
        "# Canonical scanpy: HVG → PCA → neighbors → UMAP → leiden, then marker scoring.\n"
        "\n"
        "N_TOP_GENES = 2000\n"
        "N_PCS = 50\n"
        "N_NEIGHBORS = 15\n"
        "LEIDEN_RESOLUTION = 0.5  # TODO: tune (0.3-0.8 typical)\n"
        "\n"
        "sc.pp.highly_variable_genes(adata, n_top_genes=N_TOP_GENES, flavor='seurat')\n"
        "sc.pp.scale(adata, max_value=10)\n"
        "sc.tl.pca(adata, n_comps=N_PCS)\n"
        "sc.pp.neighbors(adata, n_neighbors=N_NEIGHBORS, n_pcs=min(N_PCS, 30))\n"
        "sc.tl.umap(adata)\n"
        "sc.tl.leiden(adata, resolution=LEIDEN_RESOLUTION)\n"
        "\n"
        "print(f'leiden clusters: {adata.obs[\"leiden\"].nunique()}')\n"
        "\n"
        "# Marker-score-based cell-type calling. EDIT this dictionary for your panels.\n"
        "MARKER_PANELS = {\n"
        "    'M2_macrophage': ['CD204', 'CD163', 'MSR1', 'MARCO', 'MRC1'],\n"
        "    'M1_macrophage': ['CD68', 'NOS2', 'CXCL10', 'CXCL11'],\n"
        "    'T_cell':        ['CD3D', 'CD3E', 'CD8A', 'CD4'],\n"
        "    'NK_cell':       ['NCAM1', 'NKG7', 'GNLY'],\n"
        "    'fibroblast':    ['COL1A1', 'DCN', 'PDGFRA'],\n"
        "    'endothelial':   ['PECAM1', 'VWF', 'CDH5'],\n"
        "    'malignant':     ['SATB2', 'RUNX2'],  # TODO: substitute markers for your tumor type\n"
        "}\n"
        "\n"
        "score_cols = []\n"
        "for cell_type, markers in MARKER_PANELS.items():\n"
        "    available = [g for g in markers if g in adata.var_names]\n"
        "    if available:\n"
        "        sc.tl.score_genes(adata, available, score_name=f'{cell_type}_score')\n"
        "        score_cols.append(f'{cell_type}_score')\n"
        "        print(f'{cell_type}: scored using {len(available)}/{len(markers)} markers')\n"
        "    else:\n"
        "        print(f'{cell_type}: WARNING — no markers in panel; skipping')\n"
        "\n"
        "if score_cols:\n"
        "    scores_df = adata.obs[score_cols]\n"
        "    adata.obs['celltype'] = scores_df.idxmax(axis=1).str.replace('_score', '', regex=False)\n"
        "    adata.obs['celltype_confidence'] = scores_df.max(axis=1) - scores_df.median(axis=1)\n"
        "    print(f'cell-type calls: {adata.obs[\"celltype\"].value_counts().to_dict()}')\n"
    )


def _step_spatial_graph(step: ProtocolStep) -> str:
    return (
        f"# === Step {step.order}: {step.name} ===\n"
        "# Canonical squidpy: spatial-neighbors graph + neighborhood enrichment.\n"
        "import squidpy as sq\n"
        "\n"
        "N_SPATIAL_NEIGHBORS = 10  # k for kNN in physical-µm space\n"
        "\n"
        "if 'spatial' not in adata.obsm:\n"
        "    raise RuntimeError('adata.obsm[\"spatial\"] missing — this dataset is not spatial.')\n"
        "\n"
        "sq.gr.spatial_neighbors(\n"
        "    adata,\n"
        "    coord_type='generic',\n"
        "    n_neighs=N_SPATIAL_NEIGHBORS,\n"
        ")\n"
        "print(f'spatial graph: {adata.obsp[\"spatial_connectivities\"].nnz} edges')\n"
        "\n"
        "# Neighborhood enrichment by cell type — what tends to be near what.\n"
        "if 'celltype' in adata.obs.columns:\n"
        "    sq.gr.nhood_enrichment(adata, cluster_key='celltype', seed=RANDOM_SEED)\n"
        "    print('nhood enrichment computed (see adata.uns[\"celltype_nhood_enrichment\"])')\n"
        "\n"
        "# Per-tumor PyG graph for downstream learning.\n"
        "import torch_geometric.data as pyg_data\n"
        "\n"
        "def build_per_tumor_graph(adata_tumor):\n"
        "    coo = adata_tumor.obsp['spatial_connectivities'].tocoo()\n"
        "    edge_index = torch.tensor(np.vstack([coo.row, coo.col]), dtype=torch.long)\n"
        "    feat_genes = ['CD204', 'CD163', 'CD68', 'CD3D', 'CD8A', 'MKI67']  # TODO: tune panel\n"
        "    feat_genes = [g for g in feat_genes if g in adata_tumor.var_names]\n"
        "    X = adata_tumor[:, feat_genes].X\n"
        "    x_genes = X.toarray() if hasattr(X, 'toarray') else np.asarray(X)\n"
        "    celltype = adata_tumor.obs.get('celltype', pd.Series(['na'] * adata_tumor.n_obs)).fillna('na')\n"
        "    x_celltype = pd.get_dummies(celltype).values\n"
        "    x = torch.tensor(np.hstack([x_genes, x_celltype]), dtype=torch.float)\n"
        "    return pyg_data.Data(x=x, edge_index=edge_index)\n"
        "\n"
        "tumor_graphs = []\n"
        "if 'patient_id' in adata.obs.columns:\n"
        "    for pid in adata.obs['patient_id'].unique():\n"
        "        sub = adata[adata.obs['patient_id'] == pid].copy()\n"
        "        if 'spatial_connectivities' not in sub.obsp:\n"
        "            sq.gr.spatial_neighbors(sub, coord_type='generic', n_neighs=N_SPATIAL_NEIGHBORS)\n"
        "        tumor_graphs.append((pid, build_per_tumor_graph(sub)))\n"
        "    print(f'built {len(tumor_graphs)} per-tumor graphs')\n"
    )


def _step_train(step: ProtocolStep) -> str:
    return (
        f"# === Step {step.order}: {step.name} ===\n"
        "# GNN + classification head — skeleton with a real training loop.\n"
        "# The forward pass is real (GAT-based); swap to HGT for typed edges if your\n"
        "# hypothesis depends on edge typing.\n"
        "\n"
        "import torch_geometric.nn as pyg_nn\n"
        "from torch_geometric.loader import DataLoader\n"
        "\n"
        "HIDDEN_DIM = 64\n"
        "NUM_HEADS = 4\n"
        "NUM_LAYERS = 2\n"
        "DROPOUT = 0.2\n"
        "BATCH_SIZE = 4   # graphs per batch; small for whole-tumor graphs\n"
        "EPOCHS = 30\n"
        "LR = 1e-3\n"
        "\n"
        "class TumorClassifier(nn.Module):\n"
        "    def __init__(self, in_dim, hidden=HIDDEN_DIM, num_layers=NUM_LAYERS):\n"
        "        super().__init__()\n"
        "        self.convs = nn.ModuleList([\n"
        "            pyg_nn.GATConv(in_dim if i == 0 else hidden, hidden,\n"
        "                           heads=NUM_HEADS, concat=False, dropout=DROPOUT)\n"
        "            for i in range(num_layers)\n"
        "        ])\n"
        "        self.pool = pyg_nn.global_mean_pool\n"
        "        self.head = nn.Sequential(\n"
        "            nn.Linear(hidden, hidden),\n"
        "            nn.ReLU(),\n"
        "            nn.Dropout(DROPOUT),\n"
        "            nn.Linear(hidden, 1),\n"
        "        )\n"
        "\n"
        "    def forward(self, data):\n"
        "        x, edge_index, batch = data.x, data.edge_index, data.batch\n"
        "        for conv in self.convs:\n"
        "            x = torch.relu(conv(x, edge_index))\n"
        "        h = self.pool(x, batch)\n"
        "        return self.head(h).squeeze(-1)\n"
        "\n"
        "# TODO: assemble dataset (tumor_graphs from previous step) with patient labels\n"
        "labeled_graphs = []  # list[Data] with .y attached\n"
        "if not labeled_graphs:\n"
        "    raise NotImplementedError(\n"
        "        'Attach binary outcome labels to each per-tumor graph: graph.y = torch.tensor([label])'\n"
        "    )\n"
        "\n"
        "loader = DataLoader(labeled_graphs, batch_size=BATCH_SIZE, shuffle=True)\n"
        "in_dim = labeled_graphs[0].x.shape[1]\n"
        "model = TumorClassifier(in_dim=in_dim)\n"
        "optimizer = torch.optim.Adam(model.parameters(), lr=LR)\n"
        "loss_fn = nn.BCEWithLogitsLoss()\n"
        "\n"
        "model.train()\n"
        "for epoch in range(EPOCHS):\n"
        "    losses = []\n"
        "    for batch in loader:\n"
        "        optimizer.zero_grad()\n"
        "        logits = model(batch)\n"
        "        loss = loss_fn(logits, batch.y.float())\n"
        "        loss.backward()\n"
        "        optimizer.step()\n"
        "        losses.append(loss.item())\n"
        "    if epoch % 5 == 0:\n"
        "        print(f'epoch {epoch}: train loss = {np.mean(losses):.4f}')\n"
    )


def _step_evaluate(step: ProtocolStep) -> str:
    return (
        f"# === Step {step.order}: {step.name} ===\n"
        "# Held-out evaluation: AUROC + AUPRC + Brier + calibration curve.\n"
        "\n"
        "model.eval()\n"
        "y_true_list, y_pred_list = [], []\n"
        "with torch.no_grad():\n"
        "    for batch in loader:  # TODO: replace with held-out validation loader\n"
        "        logits = model(batch)\n"
        "        probs = torch.sigmoid(logits).cpu().numpy()\n"
        "        y_pred_list.extend(probs.tolist())\n"
        "        y_true_list.extend(batch.y.cpu().numpy().tolist())\n"
        "y_true = np.array(y_true_list)\n"
        "y_pred = np.array(y_pred_list)\n"
        "\n"
        "model_auroc = roc_auc_score(y_true, y_pred)\n"
        "model_auprc = average_precision_score(y_true, y_pred)\n"
        "model_brier = brier_score_loss(y_true, y_pred)\n"
        "print(f'AUROC: {model_auroc:.4f}')\n"
        "print(f'AUPRC: {model_auprc:.4f}')\n"
        "print(f'Brier: {model_brier:.4f}')\n"
        "\n"
        "from sklearn.calibration import calibration_curve\n"
        "prob_true, prob_pred = calibration_curve(y_true, y_pred, n_bins=10, strategy='quantile')\n"
        "for pt, pp in zip(prob_true, prob_pred):\n"
        "    print(f'  bin midpoint {pp:.2f} → observed rate {pt:.2f}')\n"
        "\n"
        "# TODO: compute baseline predictions (e.g., bulk IFN-γ score per patient).\n"
        "y_pred_baseline = None\n"
        "if y_pred_baseline is None:\n"
        "    raise NotImplementedError(\n"
        "        'Compute baseline predictions for the same held-out cohort.'\n"
        "    )\n"
        "baseline_auroc = roc_auc_score(y_true, y_pred_baseline)\n"
        "print(f'baseline AUROC: {baseline_auroc:.4f}')\n"
        "print(f'lift over baseline: {model_auroc - baseline_auroc:+.4f}')\n"
    )


def _step_generic(step: ProtocolStep) -> str:
    slug = "_".join(step.name.lower().split())[:32]
    return (
        f"# === Step {step.order}: {step.name} ===\n"
        f"# No canonical pattern matched this step name. Implement directly here.\n"
        f"# Inputs:  {', '.join(step.inputs) if step.inputs else '(none specified)'}\n"
        f"# Outputs: {', '.join(step.outputs) if step.outputs else '(none specified)'}\n"
        f"\n"
        f"def step_{step.order:02d}_{slug}():\n"
        f"    \"\"\"{step.description or step.name}\"\"\"\n"
        f"    raise NotImplementedError('TODO: implement step {step.order}')\n"
    )


# ---- Falsifiability cell ----------------------------------------------------


def _falsifiability_code(plan: ExperimentPlan) -> str:
    return (
        "# === Falsifiability check ===\n"
        f"# Primary metric: {plan.primary_metric}\n"
        f"# Success threshold: {plan.success_threshold}\n"
        f"# Null outcome:     {plan.null_outcome}\n"
        "\n"
        "try:\n"
        "    model_metric_value = float(model_auroc)\n"
        "    baseline_metric_value = float(baseline_auroc)\n"
        "except NameError:\n"
        "    model_metric_value = None\n"
        "    baseline_metric_value = None\n"
        "\n"
        "if model_metric_value is None or baseline_metric_value is None:\n"
        "    raise NotImplementedError('Run the evaluation step first, or set values manually.')\n"
        "\n"
        "lift = model_metric_value - baseline_metric_value\n"
        "print(f'primary metric (model):    {model_metric_value:.4f}')\n"
        "print(f'primary metric (baseline): {baseline_metric_value:.4f}')\n"
        "print(f'lift over baseline:        {lift:+.4f}')\n"
        "\n"
        "MIN_LIFT_FOR_HYPOTHESIS = 0.07  # TODO: align with the falsifiability threshold above\n"
        "assert lift >= MIN_LIFT_FOR_HYPOTHESIS, (\n"
        "    f'Lift {lift:+.4f} is below the falsifiability threshold {MIN_LIFT_FOR_HYPOTHESIS}. '\n"
        "    'Per the hypothesis null outcome, this run falsifies the hypothesis.'\n"
        ")\n"
        "print('falsifiability check PASSED')\n"
    )
