"""Renderers that turn a PostExecReport into the files the framework writes back.

  - 13_postexec/execution_update.md  — full human-readable update
  - risks.md (rewrite in place with status badges)
  - hypothesis.md (append "Execution Update" section, idempotent)
  - summary.json (add `postexec` block, idempotent)
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from deltasci.postexec.analyzer import PostExecReport


_BADGE = {
    "resolved": "✅ resolved",
    "still_open": "🟡 still open",
    "partly_resolved": "🟠 partly resolved",
    "confirmed": "🔴 confirmed",
    "unknown": "❔ unknown",
    "done": "✅ done",
    "outstanding": "🟡 outstanding",
    "partial": "🟠 partial",
}

_EXECUTION_UPDATE_HEADER = "<!-- deltasci:execution-update v1 -->"


def render_addendum_markdown(report: PostExecReport) -> str:
    lines: list[str] = []
    lines.append("# Execution Update\n")
    lines.append(
        "*Auto-generated by `deltasci postexec` from the executed notebook + observation cells. "
        "This is the deterministic, rule-based pass; an LLM-aided rewrite is opt-in via `--llm-rewrite`.*\n"
    )

    if report.achievements:
        lines.append("## Headline achievements\n")
        for a in report.achievements:
            anchor = f" *(cell {a.cell_index})*" if a.cell_index is not None else ""
            lines.append(f"- **{a.headline}**{anchor}")
            if a.detail:
                lines.append(f"  - {a.detail}")
        lines.append("")

    if report.metrics:
        lines.append("## Measured metrics\n")
        lines.append("| Metric | Value | From |")
        lines.append("|---|---|---|")
        for m in report.metrics:
            lines.append(f"| `{m.name}` | {m.value:.4f} | cell {m.cell_index} |")
        lines.append("")

    if report.risk_statuses:
        lines.append("## Risk register — post-execution status\n")
        lines.append("| ID | Severity | Status | Evidence |")
        lines.append("|---|---|---|---|")
        for rs in report.risk_statuses:
            ev = rs.evidence_snippet[:120].replace("|", "&#124;") if rs.evidence_snippet else rs.rationale[:120]
            lines.append(f"| **{rs.risk_id}** | {rs.severity} | {_BADGE.get(rs.status, rs.status)} | {ev} |")
        lines.append("")
        # Detailed entries with descriptions
        for rs in report.risk_statuses:
            lines.append(f"### {rs.risk_id} — {rs.severity} → {_BADGE.get(rs.status, rs.status)}")
            lines.append(f"> {rs.description}")
            if rs.evidence_snippet:
                lines.append(f"\n*Evidence (cell {rs.evidence_cell}):* `{rs.evidence_snippet}`")
            elif rs.rationale:
                lines.append(f"\n*Rationale:* {rs.rationale}")
            lines.append("")

    if report.next_step_statuses:
        lines.append("## Protocol next-steps — post-execution status\n")
        lines.append("| Step | Name | Status | Evidence |")
        lines.append("|---|---|---|---|")
        for s in report.next_step_statuses:
            ev = s.evidence_snippet[:120].replace("|", "&#124;")
            lines.append(f"| {s.order} | {s.name} | {_BADGE.get(s.status, s.status)} | {ev} |")
        lines.append("")

    if report.new_issues:
        lines.append("## New issues surfaced by execution\n")
        for ni in report.new_issues:
            lines.append(f"- *(cell {ni.cell_index})* **{ni.kind}** — {ni.message}")
            if ni.snippet:
                lines.append(f"  - `{ni.snippet}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def render_risks_markdown_with_status(original_md: str, report: PostExecReport) -> str:
    """Insert a post-execution-status badge on each `## R<n> ·` heading.

    Idempotent: looks for an existing trailing badge and replaces it.
    """
    by_id = {rs.risk_id: rs for rs in report.risk_statuses}

    def patch(line: str) -> str:
        m = re.match(r"^(##\s+R\d+\s+·.*?(?:CRITICAL|HIGH|MEDIUM|LOW|critical|high|medium|low))", line)
        if not m:
            return line
        # Strip any prior status badge appended by us
        head = m.group(1)
        rest = line[m.end():]
        rest = re.sub(r"\s*·\s*(✅\s*resolved|🟡\s*still open|🟠\s*partly resolved|🔴\s*confirmed|❔\s*unknown).*$", "", rest)
        # Find the risk by ID
        id_m = re.match(r"^##\s+(R\d+)", line)
        if not id_m:
            return head + rest
        rs = by_id.get(id_m.group(1))
        if not rs:
            return head + rest
        return f"{head} · {_BADGE.get(rs.status, rs.status)}{rest}"

    return "\n".join(patch(ln) for ln in original_md.splitlines()) + ("\n" if original_md.endswith("\n") else "")


def append_execution_update_to_hypothesis(hypothesis_md: str, addendum: str) -> str:
    """Append the addendum to the hypothesis.md, replacing any prior block (idempotent)."""
    block = f"\n\n{_EXECUTION_UPDATE_HEADER}\n{addendum.strip()}\n"
    if _EXECUTION_UPDATE_HEADER in hypothesis_md:
        return re.sub(
            re.escape(_EXECUTION_UPDATE_HEADER) + r"[\s\S]*$",
            block.lstrip("\n"),
            hypothesis_md,
        )
    return hypothesis_md.rstrip() + block


def update_summary_json(summary: dict, report: PostExecReport) -> dict:
    summary = dict(summary)
    summary["postexec"] = report.to_dict()
    return summary


def write_postexec_artifacts(run_dir: Path, report: PostExecReport) -> list[Path]:
    """Write all outputs to disk. Returns the paths that were written."""
    written: list[Path] = []
    stage = run_dir / "13_postexec"
    stage.mkdir(parents=True, exist_ok=True)

    # 1. addendum
    addendum = render_addendum_markdown(report)
    addendum_path = stage / "execution_update.md"
    addendum_path.write_text(addendum, encoding="utf-8")
    written.append(addendum_path)

    # 2. machine-readable
    json_path = stage / "report.json"
    json_path.write_text(json.dumps(report.to_dict(), indent=2), encoding="utf-8")
    written.append(json_path)

    # 3. patch risks.md
    risks_md_path = run_dir / "07_risks" / "risks.md"
    if risks_md_path.is_file():
        original = risks_md_path.read_text(encoding="utf-8")
        risks_md_path.write_text(
            render_risks_markdown_with_status(original, report),
            encoding="utf-8",
        )
        written.append(risks_md_path)

    # 4. append to hypothesis.md
    hyp_path = run_dir / "hypothesis.md"
    if hyp_path.is_file():
        hyp_path.write_text(
            append_execution_update_to_hypothesis(hyp_path.read_text(encoding="utf-8"), addendum),
            encoding="utf-8",
        )
        written.append(hyp_path)

    # 5. update summary.json
    summary_path = run_dir / "summary.json"
    if summary_path.is_file():
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        summary = update_summary_json(summary, report)
        summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
        written.append(summary_path)

    return written
